# QuantLab 默认配置

# 交易配置
trading:
  fee: 0.0008  # 手续费率 0.08%
  slippage: 0.0005  # 滑点率 0.05%
  leverage: 10  # 杠杆倍数
  equity: 5000.0  # 起始资金(USDT)
  mmr: 0.005  # 维持保证金率 0.5%
  take_profit: 0.25  # 止盈比例(杠杆后) 25%
  stop_loss: 0.05  # 止损比例(杠杆后) 5%

# 策略配置
strategy:
  cluster_pct: 0.01  # 均线簇密集阈值 1%
  retest_confirmation: false  # 是否启用回踩确认
  macd_fast: 12  # MACD快线周期
  macd_slow: 26  # MACD慢线周期
  macd_signal: 9  # MACD信号线周期
  ma_periods: [20, 60, 120]  # 均线周期

# 数据配置
data:
  exchange: binance  # 交易所
  symbols: [BTCUSDT, ETHUSDT]  # 交易对列表
  timeframes: [1h, 4h, 1d, 1w]  # 时间框架
  since: 2023-01-01  # 开始日期
  until: 2025-10-01  # 结束日期
  data_dir: data/raw  # 数据目录
  plots_dir: plots  # 图表目录
  reports_dir: reports  # 报告目录

# API 配置（可选）
api_key: null
secret_key: null
